version: "3.9"
services:
  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    networks:
      - app_default
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT = 8000
      # - NODE_ENV=production
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3   
networks:
  app_default:
    driver: bridge